import './globals.scss';

import { Inter } from 'next/font/google'
import Link from 'next/link';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SAE201',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="utf-8" />
        <meta name="keywords" content="GARE ***, ITINERAIRE, La UwU Corporation™&nbsp;est heureuse de vous présenter son nouveau chef d&amp;apos;oeuvre." />
        <meta name="description" content="" />
        <title>Accueil</title>
        {/* <link rel="stylesheet" href="nicepage.css" media="screen" /> */}
      </head>
      <body className={inter.className}>
        <header>
          <Image src="https://cdn.discordapp.com/attachments/1025038228396449803/1122612858908319811/long_logoUwU.png" alt="Logo"
            width={0}
            height={0}
            sizes="2%"
            style={{ width: '30%', height: 'auto', backgroundColor: "transparent", backgroundBlendMode: "darken" }} // optional
          />
          <nav>
            <Link href="/">Accueil</Link>
            <Link href="/Map">Carte</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
