import './globals.scss';

import { Inter } from 'next/font/google'
import Image from 'next/image'  

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta charSet="utf-8" />
      <meta name="keywords" content="GARE ***, ITINERAIRE, La UwU Corporation™&nbsp;est heureuse de vous présenter son nouveau chef d&amp;apos;oeuvre." />
      <meta name="description" content="" />
      <title>Accueil</title>
      {/* <link rel="stylesheet" href="nicepage.css" media="screen" /> */}
      </head>
      <body className={inter.className}>
        <header>
          <Image src="/images/icon.png" alt="" className="logo" />
        </header>
        {children}
        </body>
    </html>
  )
}
